version: "3.9"

services:
  postgres:
    container_name: balance_postgresdb
    image: postgres:14.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234512345"
    ports:
      - "5436:5432"

  migration:
    container_name: balance
    build:
      context: ..
      dockerfile: ./build/balance/Dockerfile
    ports:
      - "3456:3456"